apiVersion: v1
kind: Pod
metadata:
  name: dotnet-kafka-app-debug
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: dotnet-kafka-app-debug
      image: quay.io/pknezevich/dotnet-kafka-app
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
